version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: strapi
      DATABASE_PORT: 5432
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi

  backend_web:
    build: 
      context: .
      dockerfile: Dockerfile
      
