version: '3'

services:
  frontend:
    image: giftcup/strapi-frontend
    container_name: nextjs-strapi-boilerplate-frontend
    depends_on:
      - backend
    ports:
      - "80:3000"
    restart: unless-stopped
    volumes:
      - ./app:/frontend
  
  backend:
    image: strapi/strapi
    container_name: nextjs-strapi-boilerplate-backend
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "8000:1337"
    restart: on-failure
    volumes:
      - ./app:/srv/app

  db:
    container_name: nextjs-strapi-boilerplate-db
    image: postgres
    ports:
      - "8009:5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
