version: '3'

services:
  frontend:
    container_name: language-crowdsource-frontend
    build:
      context: ../frontend
    depends_on:
      - backend
    env_file:
      - ../frontend/.env
    ports:
      - "${FRONTEND_PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./app:/frontend
  
  backend:
    container_name: language-crowdsource-backend
    build:
      context: ../backend
    depends_on:
      - db
    env_file:
      - ../backend/app/.env
    ports:
      - "${BACKEND_PORT}:1337"
    restart: on-failure
    volumes:
      - ./app:/srv/app

  db:
    container_name: language-crowdsource-db
    image: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - ../backend/app/.env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
