version: '3'

services:
  db:
    container_name: language-crowdsource-db
    image: postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - ../configs/.env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: language-crowdsource-backend
    build:
      context: ../backend
    depends_on:
      - db
    env_file:
      - ../backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./app:/backend
    restart: on-failure

  frontend:
    container_name: language-crowdsource-frontend
    build:
      context: ../frontend
    depends_on:
      - backend
    env_file:
      - ../frontend/.env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./app:/frontend
    restart: unless-stopped
